@startuml
title Diagrama de Sequencia referente ao CDU001 - Editar Tarefa
actor Usuário
boundary Frontend
boundary SpringBoot
control taskController
entity Task
participant taskService
participant taskRepository
participant pagedResourcesAssembler
boundary TypedQuery
participant Hibernate
database TodoList

== Editar Tarefa ==
Usuário -> Frontend: editar tarefa
activate Usuário
activate Frontend
Frontend -> SpringBoot: PUT /api/tasks/{id}
activate SpringBoot
SpringBoot -> taskController: editTask(id, TaskDto)
activate taskController
taskController -> taskService: update(id, TaskDto)
activate taskService
taskService -> taskRepository: findById(id)
activate taskRepository
taskRepository -> Hibernate: find(Task, id)
Hibernate -> TodoList: SELECT * FROM Tasks WHERE id = id
TodoList --> Hibernate: Task
Hibernate --> taskRepository: Task
taskRepository --> taskService: Task
taskService -> taskRepository: save(Task)
taskRepository -> Hibernate: update(Task)
Hibernate -> TodoList: UPDATE Tasks SET ...
TodoList --> Hibernate: Task updated
Hibernate --> taskRepository: Task
taskRepository --> taskService: Task
taskService --> taskController: Task
taskController --> SpringBoot: ResponseEntity.ok(Task)
SpringBoot --> Frontend: ResponseEntity.ok(Task)
Frontend --> Usuário: Tarefa editada
deactivate taskRepository
deactivate taskService
deactivate taskController
deactivate SpringBoot
deactivate Frontend
deactivate Usuário
@enduml